# Dockerfile.dev

# Use the official .NET SDK image based on Debian Bookworm
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

# Install necessary build tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    clang \
    gcc \
    libc6-dev \
    libunwind-dev \
    zlib1g-dev \
  && rm -rf /var/lib/apt/lists/*

# Set the entrypoint to be the dotnet CLI
ENTRYPOINT ["dotnet"]